# Generated by Django 5.2.10 on 2026-03-16 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('reading_minute', models.PositiveIntegerField(default=5)),
                ('tg_link', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
